spring:
  application:
    name: socialMedia
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret: F{jBgE}Zcvg/6_^VSL[7d1i1tYH8a21XA%uifsOTk}^
  expiration-ms: 3600000
